CemeteryRecords:
    type: entity
    table: cemetery_records
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 500
            fixed: false
            nullable: false
        location:
            type: string
            length: 100
            fixed: false
            nullable: false
        plot:
            type: text
            nullable: false
        extra:
            type: text
            nullable: false
    lifecycleCallbacks: {  }
