parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: mvhpc
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: c2ef7fdd5984f685aee10abe10fbf3dcdc
    database_path: null
